version: "3.0"
services:
    web:
      image: webdevops/php-nginx:8.2
      container_name: web
      restart: always
      user: root
      environment:
        #- WEB_ALIAS_DOMAIN=local.mgt.vn
        - WEB_DOCUMENT_ROOT=/app/public
        - PHP_DATE_TIMEZONE=UTC
        - PHP_DISPLAY_ERRORS=1
        - PHP_MEMORY_LIMIT=2048M
        - PHP_MAX_EXECUTION_TIME=180000
        - PHP_POST_MAX_SIZE=500M
        - PHP_UPLOAD_MAX_FILESIZE=1024M
      volumes:
        - ./:/app:cached

      ports: 
        - "8080:80"
        - "443:443"  
